silence stdio warnings
previously:

```
plan.c:1603:15: warning: implicit declaration of function ‘asprintf’; did you mean ‘vsprintf’? [-Wimplicit-function-declaration]
 1603 |         ret = asprintf(&lab, "jet_dispatch: %s match pre-arg-eval+update", jet.name);
      |               ^~~~~~~~
      |               vsprintf
```

now silent. it never errored or crashed at runtime tho, which is weird. I guess
linking worked as expected?